const ReadMessages = (props:any) =>{

  
  return(
    <div>
      <h1>this page is generated by static site generation SSG</h1>
      {props.messages.map((msg:any,index:number)=>{
        return(
          <div key={index} className=" bg-red-200" >
          <h1>{msg.subject}</h1>
          <h3>from: {msg.fullName}</h3>
          <p>email: {msg.email}</p>
          <p>message: {msg.message}</p>
          <p>date : {msg.date +' - '+msg.time }</p>
        </div>
        )
      })}
    </div>
  )
}

export default ReadMessages;

export async function getStaticProps(){
  
  const data = await fetch('https://next-test-nilayp799.vercel.app/api/form/getContactMessages',{
    method:'GET',
    headers:{
      'Content-Type' : 'application/json'
    }
  }).then(res=>{return res.json()})
  .then(data=> {return data.messages})
  return{
    props:{
      messages :data,
    },
    revalidate:20
  }
}